### PR TITLE
Fix Xcode nullable warning

### PR DESCRIPTION
**Pull request by Kyle-Ye**

### CODE REVIEW

**Comment by tisfeng** [comment]
Do we need to add `nullable` to the method return value  in .m file?

```objc
- (nullable NSWindow *)window {
    NSResponder *responder = self;
    while ((responder = [responder nextResponder])) {
        if ([responder isKindOfClass:[NSWindow class]]) {
            return (NSWindow *)responder;
        }
    }
    return nil;
}
```

**Comment by liyafly** [comment]
> Do we need to add `nullable` to the method return value in .m file?
> 
> ```objc
> - (nullable NSWindow *)window {
>     NSResponder *responder = self;
>     while ((responder = [responder nextResponder])) {
>         if ([responder isKindOfClass:[NSWindow class]]) {
>             return (NSWindow *)responder;
>         }
>     }
>     return nil;
> }
> ```

Usually, it’s not necessary as it will follow the declarations in the .h file.

**Comment by liyafly** [comment]
It’s indeed necessary to add nullable to this as well. With that said, can we merge this PR? @tisfeng

**Comment by tisfeng** [comment]
Please add nullable also to the .m file, since I am used to keeping the method names in .h and .m files consistent.

**Comment by liyafly** [comment]
thanks

**Pull request merged**
